#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml
default_config:
stream:
  ll_hls: false
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
#  login_attempts_threshold: 10
#logger:
#  default: warning
#  logs:
#    homeassistant.components.zha: debug

#################################################################
## Components
#################################################################

zha:
  zigpy_config:
    network:
      chREDACTEDl: 25
      chREDACTEDls: [15, 20, 25]
    ota:
      ikea_provider: true
      ledvance_provider: true
      salus_provider: true
      inovelli_provider: true
      #otau_directory: /data/containers/homeassistant/config/zigbee-ota

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: "REDACTED, MO"

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 30
      delay_time: 30
      trigger_time: 120 
    armed_away:
      arming_time: 30
      delay_time: 15
      trigger_time: 120

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

#################################################################
## Notifications
#################################################################

notify:
  - platform: group
    name: REDACTED_devices
    services:
      - service: mobile_app_REDACTEDs_iphone
      - service: mobile_app_REDACTEDs_ipad
      - service: mobile_app_REDACTED_s_macbook_pro

  - platform: group
    name: USER2_devices
    services:
      - service: mobile_app_USER2s_iphone
      - service: mobile_app_USER2s_ipad

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
script: !include scripts.yaml
homekit: !include homekit.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
cloud: !include cloud.yaml
template: !include template.yaml