#################################################################
## 3D Printer Automations
#################################################################

        ##########################################################
        ## Prusa MK4 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Finished
  id: '3d_printer_prusa_mk4_print_finished'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa MK4)
        data:
          tag: prusa_mk4_finished
          group: 3d_printer
          entity_id: camera.prusa_mk4

        ##########################################################
        ## Prusa MK3 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa MK3 Print Finished
  id: '3d_printer_prusa_mk3_print_finished'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa MK3)
        data:
          tag: prusa_finished
          group: 3d_printer
          entity_id: camera.prusa_mk3

        ##########################################################
        ## 3D Printer On Turn On Light
        ##########################################################

- alias: 3D-Printer - Printer On Turn On Light
  id: '3d_printer_on_turn_on_light'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 50

        ##########################################################
        ## 3D Printer Off Turn Off Light Prusa MK4
        ##########################################################

- alias: 3D-Printer - Printer Off Turn Off Light Prusa MK4
  id: '3d_printer_off_turn_off_light_prusa_mini'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_mk3
        state: 'printing'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Off Turn Off Light Prusa MK3
        ##########################################################

- alias: 3D-Printer - Printer Off Turn Off Light Prusa MK3
  id: '3d_printer_off_turn_off_light_prusa_mk3'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_mk4
        state: 'printing'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Turn On Camera Recording Prusa MK3
        ##########################################################

- alias: 3D-Printer - Turn On Camera Recording Prusa MK3
  id: '3d_printer_turn_on_camera_recording_prusa_mk3'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk3_recording_mode
        state: 'Always'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk3_recording_mode
        option: "Always"

        ##########################################################
        ## 3D Printer Turn Off Camera Recording Prusa MK3
        ##########################################################

- alias: 3D-Printer - Turn Off Camera Recording Prusa MK3
  id: '3d_printer_turn_off_camera_recording_prusa_mk3'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk3_recording_mode
        state: 'Never'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk3_recording_mode
        option: "Never"

        ##########################################################
        ## 3D Printer Turn On Camera Recording Prusa MK4
        ##########################################################

- alias: 3D-Printer - Turn On Camera Recording Prusa MK4
  id: '3d_printer_turn_on_camera_recording_prusa_mini'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk4_recording_mode
        state: 'Always'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk4_recording_mode
        option: "Always"

        ##########################################################
        ## 3D Printer Turn Off Camera Recording Prusa MK4
        ##########################################################

- alias: 3D-Printer - Turn Off Camera Recording Prusa MK4
  id: '3d_printer_turn_off_camera_recording_prusa_mini'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk4_recording_mode
        state: 'Never'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk4_recording_mode
        option: "Never"
