#################################################################
## 3D Printer Automations
#################################################################

        ##########################################################
        ## Prusa MK4 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Finished
  id: '3d_printer_prusa_mk4_print_finished'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa MK4)
        data:
          tag: prusa_mk4_finished
          group: 3d_printer
          entity_id: camera.prusa_mk4

        ##########################################################
        ## Prusa MK3 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa MK3 Print Finished
  id: '3d_printer_prusa_mk3_print_finished'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa MK3)
        data:
          tag: prusa_finished
          group: 3d_printer
          entity_id: camera.prusa_mk3

        ##########################################################
        ## Prusa MK3 Print Error
        ##########################################################

- alias: 3D-Printer - Prusa MK3 Print Error
  id: '3d_printer_prusa_mk3_print_error'

  trigger:
    - platform: numeric_state
      entity_id: sensor.prusa_mk3_nozzle_temperature
      below: 160
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: sensor.prusa_mk3
      state: 'printing'

  action:
    - service: notify.USER1_devices
      data:
        message: Print Error (Prusa MK3)
        data:
          tag: prusa_error
          group: 3d_printer
          entity_id: camera.prusa_mk3

        ##########################################################
        ## Prusa MK4 Print Error
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Print Error
  id: '3d_printer_prusa_mk4_print_error'

  trigger:
    - platform: numeric_state
      entity_id: sensor.prusa_mk4_nozzle_temperature
      below: 160
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: sensor.prusa_mk4
      state: 'printing'

  action:
    - service: notify.USER1_devices
      data:
        message: Print Error (Prusa MK$)
        data:
          tag: prusa_error
          group: 3d_printer
          entity_id: camera.prusa_mk4

        ##########################################################
        ## 3D Printer On Turn On Light
        ##########################################################

- alias: 3D-Printer - Printer On Turn On Light
  id: '3d_printer_on_turn_on_light'

  trigger:
    - platform: state
      entity_id: switch.prusa_mk3
      to: 'on'
    - platform: state
      entity_id: switch.prusa_mk4
      to: 'on'

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_temp: 370

        ##########################################################
        ## 3D Printer MK4 Off Turn Off Light
        ##########################################################

- alias: 3D-Printer - MK4 Off Turn Off Light
  id: '3d_printer_MK4_off_turn_off_light'

  trigger:
    - platform: state
      entity_id: switch.prusa_mk4
      to: 'off'

  condition:
    - condition: state
      entity_id: switch.prusa_mk3
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_mk3
        state: 'printing'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer MK3 Off Turn Off Light
        ##########################################################

- alias: 3D-Printer - MK3 Off Turn Off Light
  id: '3d_printer_MK3_off_turn_off_light'

  trigger:
    - platform: state
      entity_id: switch.prusa_mk3
      to: 'off'

  condition:
    - condition: state
      entity_id: switch.prusa_mk4
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.prusa_mk4
        state: 'printing'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Light Print Start
        ##########################################################

- alias: 3D-Printer - Light Print Start
  id: '3d_printer_print_start'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_name: "blue"
    - delay: '00:15:00'
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_temp: 370

        ##########################################################
        ## 3D Printer Light Print Finish
        ##########################################################

- alias: 3D-Printer - Light Print Finish
  id: '3d_printer_light_print_finish'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_name: "green"

        ##########################################################
        ## 3D Printer Light MK4 Print Finish Reset
        ##########################################################

- alias: 3D-Printer - Light MK4 Print Finish Reset
  id: '3d_printer_light_mk4_print_finish_reset'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_temp: 370

        ##########################################################
        ## 3D Printer Light MK3 Print Finish Reset
        ##########################################################

- alias: 3D-Printer - Light MK3 Print Finish Reset
  id: '3d_printer_light_mk3_print_finish_reset'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light
      data:
        brightness_pct: 100
        color_temp: 370

        ##########################################################
        ## Prusa MK4 Enclosure Fan On
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Enclosure Fan On
  id: '3d_printer_prusa_mk4_enclosure_fan_on'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: switch.prusa_mk4_enclosure_fan
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.prusa_mk4_enclosure_fan

        ##########################################################
        ## Prusa MK4 Enclosure Fan Off
        ##########################################################

- alias: 3D-Printer - Prusa MK4 Enclosure Fan Off
  id: '3d_printer_prusa_mk4_enclosure_fan_off'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.prusa_mk4_enclosure_fan
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk4_enclosure_fan

        ##########################################################
        ## Prusa MK4 PSU Fan On
        ##########################################################

- alias: 3D-Printer - Prusa MK4 PSU Fan On
  id: '3d_printer_prusa_mk4_psu_fan_on'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: switch.prusa_mk4_psu_fan
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.prusa_mk4_psu_fan

        ##########################################################
        ## Prusa MK4 PSU Fan Off
        ##########################################################

- alias: 3D-Printer - Prusa MK4 PSU Fan Off
  id: '3d_printer_prusa_mk4_psu_fan_off'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.prusa_mk4_psu_fan
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk4_psu_fan

        ##########################################################
        ## Prusa MK3 Enclosure Fan On
        ##########################################################

- alias: 3D-Printer - Prusa MK3 Enclosure Fan On
  id: '3d_printer_prusa_mk3_enclosure_fan_on'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: switch.prusa_mk3_enclosure_fan
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.prusa_mk3_enclosure_fan

        ##########################################################
        ## Prusa MK3 Enclosure Fan Off
        ##########################################################

- alias: 3D-Printer - Prusa MK3 Enclosure Fan Off
  id: '3d_printer_prusa_mk3_enclosure_fan_off'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.prusa_mk3_enclosure_fan
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk3_enclosure_fan

        ##########################################################
        ## Prusa MK3 PSU Fan On
        ##########################################################

- alias: 3D-Printer - Prusa MK3 PSU Fan On
  id: '3d_printer_prusa_mk3_psu_fan_on'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 10

  condition:
    - condition: state
      entity_id: switch.prusa_mk3_psu_fan
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.prusa_mk3_psu_fan

        ##########################################################
        ## Prusa MK3 PSU Fan Off
        ##########################################################

- alias: 3D-Printer - Prusa MK3 PSU Fan Off
  id: '3d_printer_prusa_mk3_psu_fan_off'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.prusa_mk3_psu_fan
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk3_psu_fan

        ##########################################################
        ## 3D Printer MK4 Off Turn Off Fans
        ##########################################################

- alias: 3D-Printer - MK4 Off Turn Off Fans
  id: '3d_printer_MK4_off_turn_off_fans'

  trigger:
    - platform: state
      entity_id: switch.prusa_mk4
      to: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk4_enclosure_fan
        - switch.prusa_mk4_psu_fan

        ##########################################################
        ## 3D Printer MK3 Off Turn Off Fans
        ##########################################################

- alias: 3D-Printer - MK3 Off Turn Off Fans
  id: '3d_printer_MK3_off_turn_off_fans'

  trigger:
    - platform: state
      entity_id: switch.prusa_mk3
      to: 'off'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.prusa_mk3_enclosure_fan
        - switch.prusa_mk3_psu_fan

        ##########################################################
        ## 3D Printer Turn On Camera Recording Prusa MK3
        ##########################################################

- alias: 3D-Printer - Turn On Camera Recording Prusa MK3
  id: '3d_printer_turn_on_camera_recording_prusa_mk3'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk3_recording_mode
        state: 'Always'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk3_recording_mode
        option: "Always"

        ##########################################################
        ## 3D Printer Turn Off Camera Recording Prusa MK3
        ##########################################################

- alias: 3D-Printer - Turn Off Camera Recording Prusa MK3
  id: '3d_printer_turn_off_camera_recording_prusa_mk3'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk3
      from: 'printing'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk3_recording_mode
        state: 'Never'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk3_recording_mode
        option: "Never"

        ##########################################################
        ## 3D Printer Turn On Camera Recording Prusa MK4
        ##########################################################

- alias: 3D-Printer - Turn On Camera Recording Prusa MK4
  id: '3d_printer_turn_on_camera_recording_prusa_mini'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      to: 'printing'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk4_recording_mode
        state: 'Always'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk4_recording_mode
        option: "Always"

        ##########################################################
        ## 3D Printer Turn Off Camera Recording Prusa MK4
        ##########################################################

- alias: 3D-Printer - Turn Off Camera Recording Prusa MK4
  id: '3d_printer_turn_off_camera_recording_prusa_mini'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mk4
      from: 'printing'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: select.prusa_mk4_recording_mode
        state: 'Never'

  action:
    - service: select.select_option
      data:
        entity_id: select.prusa_mk4_recording_mode
        option: "Never"
