#################################################################
## System
#################################################################

        ##########################################################
        ## Backup Home Assistant Nightly
        ##########################################################

- alias: System - Backup Home Assistant Nightly
  id: 'system_backup_home_assistant_nightly'

  trigger:
   - platform: time
     at: '04:00:00'

  action:
    - service: backup.create

        ##########################################################
        ## Reset Overrides at 7a
        ##########################################################

- alias: System - Reset Overrides at 7a
  id: 'system_reset_overrides_at_7a'

  trigger:
   - platform: time
     at: '07:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_climate
        - input_boolean.disable_notifications
        - input_boolean.disable_doorbell
        - input_boolean.disable_door_open_lights_on
        - input_boolean.disable_exterior_on_sunset
        - input_boolean.disable_exterior_off_night
        - input_boolean.disable_auto_garage
        - input_boolean.disable_home_away
        - input_boolean.disable_interior_lights_sunset
        - input_boolean.disable_lock_unlock_doors
        - input_boolean.disable_media_lights
        - input_boolean.disable_motion
        - input_boolean.disable_occupancy
        - input_boolean.disable_rainy_day
        - input_boolean.disable_water_automations
        - input_boolean.downstairs_roomba_pause
        - input_boolean.disable_startup_notifications
        - input_boolean.disable_blinds
        - input_boolean.disable_roomba
    - service: homeassistant.turn_on
      entity_id:
        - switch.pihole

        ##########################################################
        ## Disable Erroneous Startup Notifications
        ##########################################################

- alias: System - Disable Erroneous Startup Notifications
  id: 'system_disable_erroneous_startup_notifications'

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.disable_startup_notifications
    - delay: 00:02:00
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_startup_notifications

        #################################################################
        ## Clear Erroneous Failed Login Notifications
        #################################################################

- alias: System - Clear Erroneous Failed Login Notifications
  id: 'system_clear_erroneous_failed_login_notifications'

  trigger:
    - platform: state
      entity_id: persistent_notification.http_login
      to: 'notifying'

  action:
    - delay: "00:00:01"
    - service: persistent_notification.dismiss
      data:
        notification_id: http-login

        #################################################################
        ## Ping Locks if they become Unavailable
        #################################################################

- alias: System - Ping Locks if they become Unavailable
  id: 'system_ping_locks_if_they_become_unavailable'

  trigger:
    - platform: state
      entity_id: lock.front_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - platform: state
      entity_id: lock.back_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    - platform: state
      entity_id: lock.basement_door
      to: 'unavailable'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  action:
    - service: zwave_js.ping
      target:
        entity_id: 
          - lock.front_door
          - lock.back_door
          - lock.basement_door

        #################################################################
        ## Turn On USER1 Office Do not Disturb when MacBook AV Input On
        #################################################################

- alias: System - Turn On USER1 Office Do not Disturb when MacBook AV Input On
  id: 'system_turn_on_USER1_office_do_not_disturb_when_macbook_av_input_on'

  trigger:
    - platform: state
      entity_id: binary_sensor.USER1s_macbook_pro_camera_in_use
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - platform: state
      entity_id: binary_sensor.USER1s_macbook_pro_audio_input_in_use
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0
    - platform: state
      entity_id: binary_sensor.USER1s_macbook_pro_focus
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: binary_sensor.USER1s_macbook_pro_active
      state: 'on'
    - condition: state
      entity_id: input_boolean.USER1_s_office_do_not_disturb
      state: 'off'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.USER1_s_office_do_not_disturb

#################################################################
## Notifications
#################################################################

        #################################################################
        ## NAS-01 Warning iOS Notification
        #################################################################

- alias: System - NAS-01 Warning iOS Notification
  id: 'system_nas_01_warning_ios_notification'

  trigger:
    - platform: state
      entity_id: sensor.nas_01_status
      to: 'warning'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: NAS-01 RAID Failing
        data:
          tag: nas
          group: system

        #################################################################
        ## NAS Warning iOS Notification
        #################################################################

- alias: System - NAS-02 Warning iOS Notification
  id: 'system_nas_02_warning_ios_notification'

  trigger:
    - platform: state
      entity_id: sensor.nas_02_status
      to: 'warning'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: NAS-02 RAID Failing
        data:
          tag: nas
          group: system

        ##########################################################
        ## UPS Power Loss Alert iOS Notification
        ##########################################################

- alias: System - UPS Power Loss Alert iOS Notification
  id: 'system_ups_power_loss_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: 
          - sensor.ups_a_input_voltage
          - sensor.ups_b_input_voltage
      below: 80

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Power Outage Detected
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Power Restored Alert iOS Notification
        ##########################################################

- alias: System - UPS Power Restored Alert iOS Notification
  id: 'system_ups_power_restored_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: 
          - sensor.ups_a_input_voltage
          - sensor.ups_b_input_voltage
      above: 110

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_startup_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Power Restored
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Low Battery Alert iOS Notification
        ##########################################################

- alias: System - UPS Low Battery Alert iOS Notification
  id: 'system_ups_low_battery_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: 
          - sensor.ups_a_battery_charge
          - sensor.ups_b_battery_charge
      below: 15

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} Low"
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Disconnected iOS Notification
        ##########################################################

- alias: System - UPS Disconnected iOS Notification
  id: 'system_ups_disconnected_ios_notification'

  trigger:
    - platform: state
      entity_id: 
        - sensor.ups_a_status
        - sensor.ups_b_status
      to: 'unavailable'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: "{{ trigger.to_state.attributes.friendly_name }} has Disconnected"
        data:
          tag: ups
          group: system

        #################################################################
        ## Home Assistant Started iOS Notification
        #################################################################

- alias: System - Home Assistant Start iOS Notification
  id: 'system_home_assistant_start_ios_notification'

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Home Assistant Started
        data:
          tag: homeassistant
          group: system

        #################################################################
        ## Home Assistant Update iOS Notification
        #################################################################

- alias: System - Home Assistant Update iOS Notification
  id: 'system_home_assistant_update_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.docker_hub_update_available
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Update Available for Home Assistant
        data:
          tag: homeassistant
          group: system